"""Build the static site assets from the Python engine.

WHY THE SITE IS STATIC
----------------------
Stage 2 is deterministic, so every answer for a known word can be precomputed.
The whole 139,219-entry dictionary is 3.8 MB as plain text and 0.93 MB gzipped,
which a browser downloads once. That removes the server entirely: no functions,
no cold starts, no runtime cost, and the page works offline after first load.

WHAT IS GENERATED VS HAND-WRITTEN
---------------------------------
Everything data-shaped is generated here -- the dictionary, the abbreviation
table, the acronym letter names, the gazetteer, the punctuation map -- so the
browser and the Python engine cannot drift apart. Only the page itself and the
tokenizer logic are hand-written, and the tokenizer's regex is emitted from the
Python one rather than retyped.

Two outputs:
  web/public/                     deploy this anywhere static
  web/en2thaana-standalone.html   one self-contained file, works from file://

    python build_web.py
"""
from __future__ import annotations

import base64
import gzip
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from en2thaana import gazetteer, render  # noqa: E402
from en2thaana import ipa as IPA  # noqa: E402
from en2thaana.text import ABBREV, ARABIC_PUNCT, LETTER_NAMES, _TOKEN  # noqa: E402

OUT = ROOT / "web" / "public"

NL = "\n"
TAB = "\t"


def build_assets() -> dict:
    OUT.mkdir(parents=True, exist_ok=True)

    lines, sources = [], {}
    for line in (ROOT / "dist" / "en_thaana.jsonl").open(encoding="utf-8"):
        r = json.loads(line)
        lines.append(r["word"] + TAB + r["thaana"])
        sources[r["source"]] = sources.get(r["source"], 0) + 1
    dict_txt = NL.join(lines)
    (OUT / "dict.txt").write_text(dict_txt, encoding="utf-8", newline=NL)

    # The rule engine's tables, so the browser can render phonemes the model
    # invents for a word no dictionary has. The orthographic table is exported
    # ALREADY FILTERED by the confidence guard, so the JS port cannot apply a
    # different threshold than the Python engine does.
    cons, vows, coda, orth = render._tables()
    engine = {
        "cons": cons,
        "vows": vows,
        "coda": coda,
        "orth": {p + "|" + o: f for (p, o), f in orth.items()},
        "phonemes": sorted(IPA.PHONEMES, key=len, reverse=True),
        "normalise": IPA._NORMALISE,
        "drop": IPA._DROP,
        "expand": IPA.EXPAND,
        "vowelChars": IPA.VOWEL_PHONE_CHARS,
        "split": render.SPLIT_DIPHTHONGS,
        "glide": {"fili": render.GLIDE_FILI, "carrier": render.GLIDE_CARRIER,
                  "shorten": render.SHORTEN},
        "alifu": "އ",
        "sukun": "ް",
        "fili": list(__import__("en2thaana.thaana", fromlist=["FILI"]).FILI),
    }

    data = {
        "engine": engine,
        "tokenRe": _TOKEN.pattern,
        "punct": ARABIC_PUNCT,
        "letters": LETTER_NAMES,
        "abbrev": ABBREV,
        "gazetteer": gazetteer._table(),
        "counts": {"dict": len(lines), "gazetteer": gazetteer.size()},
    }
    js = ("// GENERATED by build_web.py -- do not edit." + NL
          + "// Mirrors en2thaana/text.py so the browser and the Python engine"
          + NL + "// cannot drift apart." + NL
          + "export const DATA = " + json.dumps(data, ensure_ascii=False) + ";" + NL)
    (OUT / "data.js").write_text(js, encoding="utf-8", newline=NL)

    gz = len(gzip.compress(dict_txt.encode("utf-8"), 9))
    print(f"dict.txt   {len(lines):,} entries"
          f"   {len(dict_txt.encode('utf-8'))/1e6:.1f} MB raw   {gz/1e6:.2f} MB gzipped")
    print(f"data.js    {len(js.encode('utf-8'))/1e3:.0f} KB"
          f"   ({len(data['gazetteer'])} place names, {len(ABBREV)} abbreviations)")
    print("sources    " + str(dict(sorted(sources.items(), key=lambda kv: -kv[1]))))
    return data


def build_standalone() -> None:
    """One self-contained .html: no server, no hosting, works from file://.

    The multi-file build is the one to deploy -- a host serves dict.txt
    compressed, so the browser pulls about 0.93 MB. This inlines everything
    instead, which is larger but can be double-clicked, emailed or carried on a
    stick. Generated from the same sources, so the two cannot disagree.
    """
    html = (OUT / "index.html").read_text(encoding="utf-8")
    app = (OUT / "app.js").read_text(encoding="utf-8")
    data = (OUT / "data.js").read_text(encoding="utf-8")
    dic = (OUT / "dict.txt").read_text(encoding="utf-8")
    font = base64.b64encode((OUT / "Faruma.woff2").read_bytes()).decode()

    html = html.replace(
        'src: url("Faruma.woff2") format("woff2");',
        'src: url("data:font/woff2;base64,' + font + '") format("woff2");')

    # module -> plain script: drop the imports and exports, and replace the
    # fetching load() with one that builds the map from the inlined text.
    app = app.replace('import { DATA } from "./data.js";', "")
    app = re.sub(r"export async function load\(onProgress\) \{.*?\n\}\n", "",
                 app, flags=re.S)
    app = app.replace("export ", "")

    # The rule engine comes too, so an unknown word can still be written out if
    # the model is ever reachable. From file:// it will not be -- fetch cannot
    # read the .onnx files off disk -- and g2p.js reports that rather than
    # failing silently.
    engine = (OUT / "engine.js").read_text(encoding="utf-8")
    engine = engine.replace('import { DATA } from "./data.js";', "")
    engine = engine.replace("export ", "")
    g2p = (OUT / "g2p.js").read_text(encoding="utf-8")
    g2p = g2p.replace('import { convert } from "./engine.js";', "")
    g2p = g2p.replace("export ", "")
    # its exports are referenced as g2p.* by the page
    g2p += NL + "const g2p = { load, isLoaded, phonemesFor, transcribeUnknown };" + NL

    data_obj = data.split("export const DATA = ", 1)[1].rstrip().rstrip(";")

    head = [
        "const DATA = " + data_obj + ";",
        "const DICT_TEXT = " + json.dumps(dic, ensure_ascii=False) + ";",
        "async function load(onProgress){",
        "  if (onProgress) onProgress(1);",
        "  DICT = new Map();",
        "  for (const line of DICT_TEXT.split(String.fromCharCode(10))) {",
        "    const i = line.indexOf(String.fromCharCode(9));",
        "    if (i > 0) DICT.set(line.slice(0, i), line.slice(i + 1));",
        "  }",
        "  return DICT.size;",
        "}",
    ]

    page = html.split('<script type="module">', 1)[1].rsplit("</script>", 1)[0]
    page = page.replace('import { load, transcribe } from "./app.js";', "")
    page = page.replace('import { DATA } from "./data.js";', "")
    page = page.replace('import * as g2p from "./g2p.js";', "")

    merged = ("<script>" + NL + NL.join(head) + NL + engine + NL + app + NL
              + g2p + NL + page + NL + "</script>")
    html = (html.split('<script type="module">', 1)[0] + merged
            + html.rsplit("</script>", 1)[1])

    dest = ROOT / "web" / "en2thaana-standalone.html"
    dest.write_text(html, encoding="utf-8", newline=NL)
    print(f"standalone {dest.stat().st_size/1e6:.1f} MB   {dest.name}"
          f"   (open it directly, no server)")


def main() -> None:
    build_assets()
    build_standalone()
    # The JS engine is a port of the Python one and ports drift. Both are run
    # over every shipped word and compared; a divergence would otherwise only
    # show on words the model invents, which are exactly the words that have no
    # reference spelling to notice it against.
    import verify_js
    if verify_js.main() != 0:
        raise SystemExit("the JS engine disagrees with Python; not shipping")


if __name__ == "__main__":
    main()
